src/Entity/Currency.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\EntityIdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CurrencyRepository")
 */
class Currency
{
    use EntityIdTrait;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $currency_title;

    /**
     * @ORM\Column(type="string", length=3)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=12, nullable=true)
     */
    private $symbol_left;

    /**
     * @ORM\Column(type="string", length=12, nullable=true)
     */
    private $symbol_right;

    public function getCurrencyTitle(): ?string
    {
        return $this->currency_title;
    }

    public function setCurrencyTitle(string $currency_title): self
    {
        $this->currency_title = $currency_title;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getSymbolLeft(): ?string
    {
        return $this->symbol_left;
    }

    public function setSymbolLeft(?string $symbol_left): self
    {
        $this->symbol_left = $symbol_left;

        return $this;
    }

    public function getSymbolRight(): ?string
    {
        return $this->symbol_right;
    }

    public function setSymbolRight(?string $symbol_right): self
    {
        $this->symbol_right = $symbol_right;

        return $this;
    }
}

src/Entity/Property.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\EntityIdTrait;
use App\Entity\Traits\EntityLocationTrait;
use App\Entity\Traits\EntityMetaTrait;
use App\Entity\Traits\EntityTimestampableTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{
    use EntityIdTrait;
    use EntityLocationTrait;
    use EntityMetaTrait;
    use EntityTimestampableTrait;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\DealType", inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $deal_type;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="properties")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $bathrooms_number;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $bedrooms_number;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $max_guests;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $show_map;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $price_type;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $available_now;

    /**
     * @ORM\Column(type="string", length=255, options={"default": "pending"})
     */
    private $state = 'published';

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Photo", mappedBy="property", orphanRemoval=true)
     * @ORM\OrderBy({"sort_order" = "ASC"})
     */
    private $photos;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Feature", inversedBy="properties")
     */
    private $features;

    /**
     * @ORM\Column(type="integer")
     */
    private $priority_number;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
        $this->features = new ArrayCollection();
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getDealType(): ?DealType
    {
        return $this->deal_type;
    }

    public function setDealType(?DealType $dealType): self
    {
        $this->deal_type = $dealType;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getBathroomsNumber(): ?int
    {
        return $this->bathrooms_number;
    }

    public function setBathroomsNumber(?int $bathrooms_number): self
    {
        $this->bathrooms_number = $bathrooms_number;

        return $this;
    }

    public function getBedroomsNumber(): ?int
    {
        return $this->bedrooms_number;
    }

    public function setBedroomsNumber(?int $bedrooms_number): self
    {
        $this->bedrooms_number = $bedrooms_number;

        return $this;
    }

    public function getShowMap(): ?bool
    {
        return $this->show_map;
    }

    public function setShowMap(?bool $show_map): self
    {
        $this->show_map = $show_map;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getPriceType(): ?string
    {
        return $this->price_type;
    }

    public function setPriceType(?string $price_type): self
    {
        $this->price_type = $price_type;

        return $this;
    }

    public function getAvailableNow(): ?bool
    {
        return $this->available_now;
    }

    public function setAvailableNow(?bool $available_now): self
    {
        $this->available_now = $available_now;

        return $this;
    }

    public function getPhotos(): Collection
    {
        return $this->photos;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photos->contains($photo)) {
            $this->photos[] = $photo;
            $photo->setProperty($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photos->contains($photo)) {
            $this->photos->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getProperty() === $this) {
                $photo->setProperty(null);
            }
        }

        return $this;
    }

    public function getFeatures(): Collection
    {
        return $this->features;
    }

    public function addFeature(Feature $feature): self
    {
        if (!$this->features->contains($feature)) {
            $this->features[] = $feature;
        }

        return $this;
    }

    public function removeFeature(Feature $feature): self
    {
        if ($this->features->contains($feature)) {
            $this->features->removeElement($feature);
        }

        return $this;
    }

    public function getPriorityNumber(): ?int
    {
        return $this->priority_number;
    }

    public function setPriorityNumber(?int $priority_number): self
    {
        $this->priority_number = $priority_number;

        return $this;
    }

    public function getMaxGuests(): ?int
    {
        return $this->max_guests;
    }

    public function setMaxGuests(?int $max_guests): self
    {
        $this->max_guests = $max_guests;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function isPublished(): bool
    {
        return 'published' === $this->state;
    }
}

src/Controller/Admin/PropertyController.php
<?php

declare(strict_types=1);

namespace App\Controller\Admin;

use App\Entity\Property;
use App\Form\Type\PropertyType;
use App\Repository\FilterRepository;
use App\Service\Admin\PropertyService;
use App\Transformer\RequestToArrayTransformer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class PropertyController extends AbstractController
{
    /**
     * @var PropertyService
     */
    private $service;

    public function __construct(PropertyService $service)
    {
        $this->service = $service;
    }

    /**
     * @Route("/admin/property", defaults={"page": "1"}, methods={"GET"}, name="admin_property")
     */
    public function index(Request $request, FilterRepository $repository, RequestToArrayTransformer $transformer): Response
    {
        $searchParams = $transformer->transform($request);
        $properties = $repository->findByFilter($searchParams);

        return $this->render('admin/property/index.html.twig', [
            'properties' => $properties,
            'searchParams' => $searchParams,
        ]);
    }

    /**
     * @Route("/admin/property/new", name="admin_property_new")
     */
    public function new(Request $request): Response
    {
        $property = new Property();
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->service->create($property);

            return $this->redirectToRoute('admin_photo_edit', ['id' => $property->getId()]);
        }

        return $this->render('admin/property/new.html.twig', [
            'property' => $property,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Displays a form to edit an existing Property entity.
     *
     * @Route("/admin/property/{id<\d+>}/edit",methods={"GET", "POST"}, name="admin_property_edit")
     */
    public function edit(Request $request, Property $property): Response
    {
        $form = $this->createForm(PropertyType::class, $property);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->service->update($property);

            return $this->redirectToRoute('admin_property');
        }

        return $this->render('admin/property/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * Deletes a Property entity.
     *
     * @Route("/property/{id<\d+>}/delete", methods={"POST"}, name="admin_property_delete")
     * @IsGranted("ROLE_ADMIN")
     */
    public function delete(Request $request, Property $property): Response
    {
        if (!$this->isCsrfTokenValid('delete', $request->request->get('token'))) {
            return $this->redirectToRoute('admin_property');
        }

        $this->service->delete($property);

        return $this->redirectToRoute('admin_property');
    }
}

src/Controller/PropertyController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Property;
use App\Repository\FilterRepository;
use App\Repository\PropertyRepository;
use App\Repository\SimilarRepository;
use App\Service\URLService;
use App\Transformer\RequestToArrayTransformer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

final class PropertyController extends BaseController
{
    /**
     * @Route("/", defaults={"page": "1"}, methods={"GET"}, name="property")
     */
    public function search(Request $request, FilterRepository $repository, RequestToArrayTransformer $transformer): Response
    {
        $searchParams = $transformer->transform($request);
        $properties = $repository->findByFilter($searchParams);

        return $this->render('property/index.html.twig',
            [
                'site' => $this->site(),
                'properties' => $properties,
                'searchParams' => $searchParams,
            ]
        );
    }

    /**
     * @Route("/map", methods={"GET"}, name="map_view")
     */
    public function mapView(PropertyRepository $repository): Response
    {
        return $this->render('property/map.html.twig',
            [
                'site' => $this->site(),
                'properties' => $repository->findAllPublished(),
            ]
        );
    }

    /**
     * @Route("/{citySlug}/{slug}/{id<\d+>}", methods={"GET"}, name="property_show")
     * @IsGranted("PROPERTY_VIEW", subject="property", message="Properties can only be shown to their owners.")
     */
    public function propertyShow(Request $request, URLService $url, Property $property, SimilarRepository $repository): Response
    {
        if (!$url->isCanonical($property, $request)) {
            return $this->redirect($url->generateCanonical($property), 301);
        } elseif ($url->isRefererFromCurrentHost($request)) {
            $show_back_button = true;
        }

        return $this->render('property/show.html.twig',
            [
                'site' => $this->site(),
                'property' => $property,
                'properties' => $repository->findSimilarProperties($property),
                'number_of_photos' => \count($property->getPhotos()),
                'show_back_button' => $show_back_button ?? false,
            ]
        );
    }
}

templates/property/partials/_contact_widget.html.twig
<div class="card full-xs mb-3">
    <h5 class="card-header">{{ 'widget.contact_information' | trans }}</h5>

    <div class="contact-box">
        <div class="row">
            <div class="col-auto">
                <div class="icon-box">
                    <i class="fas fa-user-tie float-icon"></i>
                </div>
            </div>
            <div class="col-auto">
                <h4>{{ 'widget.agent' | trans }}</h4>

                <p>{{ property.author.fullName }}</p>
            </div>
        </div>
    </div>

    <div class="contact-box">
        <div class="row">
            <div class="col-auto">
                <div class="icon-box">
                    <i class="fas fa-phone-square float-icon"></i>
                </div>
            </div>
            <div class="col-auto">
                <h4>{{ 'widget.phone' | trans }}</h4>

                <p><a href="tel:{{ property.author.phone }}">{{ property.author.phone }}</a></p>
            </div>
        </div>
    </div>

    <div class="contact-box">
        <div class="row">
            <div class="col-auto">
                <div class="icon-box">
                    <i class="fas fa-envelope float-icon"></i>
                </div>
            </div>
            <div class="col-auto">
                <h4>{{ 'widget.email' | trans }}</h4>

                <p><a href="mailto:{{ property.author.email }}">{{ property.author.email }}</a></p>
            </div>
        </div>
    </div>

</div>

templates/property/partials/_overview.html.twig
<div class="overview">
    <table>
        <tbody>
        <tr>
            <th>{{ 'property.location' | trans }}:</th>
            <td>
                {% if property.neighborhood.name | default %}
                    {{ property.neighborhood.name }},
                {% elseif property.district.name | default %}
                    {{ property.district.name }},
                {% endif %}
                <a href="{{ path('city', {slug: property.city.slug}) }}">{{ property.city.name }}</a>
            </td>
        </tr>

        {% if property.metroStation %}

            <tr>
                <th>{{ 'metro_station' | trans }}:</th>
                <td>{{ property.metroStation.name }}</td>
            </tr>

        {% endif %}

        <tr>
            <th>{{ 'property.deal_type' | trans }}:</th>
            <td>{{ property.dealType.name }}</td>
        </tr>
        <tr>
            <th>{{ 'property.category' | trans }}:</th>
            <td>{{ property.category.name }}</td>
        </tr>

        {% if property.bathroomsNumber != '' %}

            <tr>
                <th>{{ 'property.bathrooms' | trans }}:</th>
                <td>{{ property.bathroomsNumber }}</td>
            </tr>

        {% endif %}

        {% if property.bedroomsNumber != '' %}

            <tr>
                <th>{{ 'property.bedrooms' | trans }}:</th>
                <td>{{ property.bedroomsNumber }}</td>
            </tr>

        {% endif %}

        {% if property.maxGuests != '' %}

            <tr>
                <th>{{ 'property.max_guests' | trans }}:</th>
                <td>{{ property.maxGuests }}</td>
            </tr>

        {% endif %}

        {% if property.availableNow == '1' %}

            <tr>
                <th>{{ 'property.available_now' | trans }}:</th>
                <td>{{ 'yes' | trans }}</td>
            </tr>

        {% endif %}

        {% if property.price != '' %}

            <tr>
                <th>{{ 'property.price' | trans }}:</th>
                <td>{{ site.currency.symbolLeft }}{{ property.price }}
                    {{ site.currency.symbolRight }}

                    {% if property.priceType != '' %}
                        / {{ property.priceType }}
                    {% endif %}
                </td>
            </tr>

        {% endif %}

        </tbody>
    </table>
</div>

templates/property/partials/_search_form.html.twig
<div class="header"
     style="background-image: url(
     {% if site.header_image == '' %}
         {{ asset('/images/bg-1.5.jpg') }}
     {% else %}
         '/uploads/images/full/{{ site.header_image }}'
     {% endif %}
         )">
    <div class="header-overlay"></div>
    <div class="container">
        <div class="search_form">
            <form action="{{ path('property') }}" method="get">
                <div class="form-row justify-content-end">

                    {% if site.show_filter_by_city == '1' %}
                        <div class="col-lg-3 mb-2">
                            <select name="city" class="form-control form-control-lg" aria-label="{{ 'city'|trans }}">
                                <option value="0">{{ 'city'|trans }}</option>

                                {% for city in site.cities %}

                                    <option value="{{ city.id }}"
                                        {% if searchParams.city == city.id %} selected{% endif %}>
                                        {{ city.name }}
                                    </option>

                                {% endfor %}

                            </select>
                        </div>
                    {% endif %}

                    {% if site.show_filter_by_deal_type == '1' %}
                        <div class="col-lg-3 mb-2">
                            <select name="deal_type" class="form-control form-control-lg"
                                    aria-label="{{ 'deal_type'|trans }}">
                                <option value="0">{{ 'deal_type'|trans }}</option>

                                {% for deal_type in site.deal_types %}

                                    <option value="{{ deal_type.id }}"
                                        {% if searchParams.deal_type == deal_type.id %} selected{% endif %}
                                    >
                                        {{ deal_type.name }}
                                    </option>

                                {% endfor %}

                            </select>
                        </div>
                    {% endif %}

                    {% if site.show_filter_by_category == '1' %}
                        <div class="col-lg-3 mb-2">
                            <select name="category" class="form-control form-control-lg"
                                    aria-label="{{ 'category'|trans }}">
                                <option value="0">{{ 'category'|trans }}</option>

                                {% for category in site.categories %}

                                    <option value="{{ category.id }}"
                                        {% if searchParams.category == category.id %} selected{% endif %}
                                    >{{ category.name }}
                                    </option>

                                {% endfor %}

                            </select>
                        </div>
                    {% endif %}

                    {% if site.show_filter_by_bedrooms == '1' %}
                        <div class="col-lg-3 mb-2">
                            <select name="bedrooms" class="form-control form-control-lg"
                                    aria-label="{{ 'label.bedrooms_number'|trans }}">
                                <option value="0">{{ 'property.bedrooms'|trans }}</option>
                                <option value="0">{{ 'option.any'|trans }}</option>
                                <option value="1" {% if searchParams.bedrooms == 1 %} selected{% endif %}>
                                    1 {{ 'option.bedroom'|trans }}
                                </option>
                                <option value="2" {% if searchParams.bedrooms == 2 %} selected{% endif %}>
                                    2 {{ 'option.bedrooms'|trans }}
                                </option>
                                <option value="3" {% if searchParams.bedrooms == 3 %} selected{% endif %}>
                                    3 {{ 'option.bedrooms'|trans }}
                                </option>
                                <option value="4" {% if searchParams.bedrooms == 4 %} selected{% endif %}>
                                    4+ {{ 'option.bedrooms'|trans }}
                                </option>
                            </select>
                        </div>
                    {% endif %}

                    {% if site.show_filter_by_guests == '1' %}
                        <div class="col-lg-3 mb-2">
                            <select name="guests" class="form-control form-control-lg"
                                    aria-label="{{ 'label.guests'|trans }}">
                                <option value="0">{{ 'label.guests'|trans }}</option>
                                <option value="0">{{ 'option.any'|trans }}</option>
                                {% for i in range(1,8) %}
                                    <option value="{{ i }}"
                                        {% if searchParams.guests == i %} selected{% endif %}
                                    >{{ i }}</option>
                                {% endfor %}
                                <option value="9" {% if searchParams.guests == 9 %} selected{% endif %}>9+</option>
                            </select>
                        </div>
                    {% endif %}

                    <div class="col-lg-3 mb-2">
                        <button class="btn btn-block btn-lg btn-primary">
                            <i class="fas fa-search"></i> {{ 'action.search'|trans }}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

templates/property/partials/_search_widget.html.twig
<div class="card full-xs mb-3">
    <h5 class="card-header">{{ 'widget.search' | trans }}</h5>
    <div class="card-body">
        <form action="{{ path('property') }}" method="get">

            {% if site.show_filter_by_city == '1' %}
                <div class="form-group">
                    <label for="city">{{ 'city'|trans }}</label>
                    <select name="city" id="city" class="form-control form-control-lg">

                        <option value="0">{{ 'widget.all_cities'|trans }}</option>

                        {% for city in site.cities %}

                            <option value="{{ city.id }}">{{ city.name }}</option>

                        {% endfor %}
                    </select>
                </div>
            {% endif %}

            {% if site.show_filter_by_deal_type == '1' %}
                <div class="form-group">
                    <label for="dealType">{{ 'deal_type'|trans }}</label>
                    <select name="dealType" id="dealType" class="form-control form-control-lg">
                        <option value="0">{{ 'widget.all_deal_types'|trans }}</option>

                        {% for deal_type in site.deal_types %}

                            <option value="{{ deal_type.id }}">{{ deal_type.name }}</option>

                        {% endfor %}
                    </select>
                </div>
            {% endif %}

            {% if site.show_filter_by_category == '1' %}
                <div class="form-group">
                    <label for="category">{{ 'category'|trans }}</label>
                    <select name="category" id="category" class="form-control form-control-lg">
                        <option value="0">{{ 'widget.all_categories'|trans }}</option>

                        {% for category in site.categories %}

                            <option value="{{ category.id }}">{{ category.name }}</option>

                        {% endfor %}
                    </select>
                </div>
            {% endif %}

            {% if site.show_filter_by_bedrooms == '1' %}
                <div class="form-group">
                    <label for="bedrooms">{{ 'label.bedrooms_number'|trans }}</label>
                    <select name="bedrooms" id="bedrooms" class="form-control form-control-lg">
                        <option value="0">{{ 'property.bedrooms'|trans }}</option>
                        <option value="0">{{ 'option.any'|trans }}</option>
                        <option value="1">1 {{ 'option.bedroom'|trans }}</option>
                        <option value="2">2 {{ 'option.bedrooms'|trans }}</option>
                        <option value="3">3 {{ 'option.bedrooms'|trans }}</option>
                        <option value="4">4+ {{ 'option.bedrooms'|trans }}</option>
                    </select>
                </div>
            {% endif %}

            {% if site.show_filter_by_bedrooms == '1' %}
                <div class="form-group">
                    <label for="guests">{{ 'label.guests'|trans }}</label>
                    <select name="guests" id="guests" class="form-control form-control-lg">
                        <option value="0">{{ 'label.guests'|trans }}</option>
                        <option value="0">{{ 'option.any'|trans }}</option>
                        {% for i in range(1,8) %}
                            <option value="{{ i }}">{{ i }}</option>
                        {% endfor %}
                        <option value="9">9+</option>
                    </select>
                </div>
            {% endif %}

            <div class="form-group">
                <button class="btn btn-block btn-lg btn-primary">
                    <i class="fas fa-search"></i> {{ 'action.search'|trans }}
                </button>
            </div>
        </form>
    </div>
</div>

templates/property/partials/_similar_properties.html.twig
<h4 class="mb-4">{{ 'similar_properties'|trans }}</h4>

<div class="row">

    {% for property in properties %}

        <!-- Item -->
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="card full-xs">

                <div class="property-box-img">

                    <a href="{{ path('property_show', {
                        'id':  property.id,
                        'citySlug': property.city.slug,
                        'slug': property.slug}) }}">

                        {% for photo in property.photos | slice(0, 1) %}

                            <img class="card-img-top lazyload" src="{{ asset('/images/transparent.png') }}"
                                 data-src="/uploads/images/small/{{ photo.photo }}"
                                 alt="{{ property.address }}"
                                 title="{{ property.address }}"/>

                        {% else %}

                            <img class="card-img-top border-bottom" src="{{ asset('/images/no-photo.png') }}"
                                 alt="{{ property.address }}"
                                 title="{{ property.address }}"/>

                        {% endfor %}

                        {% if property.price != '' %}
                            <span class="price">
                                    {{ site.currency.symbolLeft }}{{ property.price }}
                                {{ site.currency.symbolRight }}

                                {% if property.priceType != '' %}
                                    / {{ property.priceType }}
                                {% endif %}
                                </span>
                        {% endif %}
                    </a>
                </div>

                <div class="card-body">
                    <h5 class="card-title">
                        <a href="{{ path('property_show', {
                            'id':  property.id,
                            'citySlug': property.city.slug,
                            'slug': property.slug}) }}">
                            {{ property.title }}
                        </a>
                    </h5>
                    <p class="small icon-green">
                        <i class="fas fa-map-marker-alt"></i> {{ property.address }}
                    </p>

                    {% if property.metroStation %}
                        <p class="small icon-green">
                            <i class="fas fa-subway"></i> {{ property.metroStation.name }}
                        </p>
                    {% endif %}

                    <span class="attribute">{{ property.dealType.name }}</span>
                    <span class="attribute">{{ property.category.name }}</span>

                    {% if property.bedroomsNumber %}
                        <span
                            class="attribute">{{ 'property.bedrooms'|trans }}: {{ property.bedroomsNumber }}</span>
                    {% endif %}
                </div>
            </div>
            <br>
        </div>
        <!-- / Item -->

    {% endfor %}

</div>