src/Entity/Menu.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\EntityIdTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MenuRepository")
 */
class Menu
{
    use EntityIdTrait;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $sort_order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $nofollow;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $new_tab;

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSortOrder(): ?int
    {
        return $this->sort_order;
    }

    public function setSortOrder(?int $sort_order): self
    {
        $this->sort_order = $sort_order;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getNofollow(): ?bool
    {
        return $this->nofollow;
    }

    public function setNofollow(?bool $nofollow): self
    {
        $this->nofollow = $nofollow;

        return $this;
    }

    public function getNewTab(): ?bool
    {
        return $this->new_tab;
    }

    public function setNewTab(?bool $new_tab): self
    {
        $this->new_tab = $new_tab;

        return $this;
    }
}

templates/layout/partials/_navbar.thml.twig
<nav class="navbar {% if site.fixed_top_navbar == '1' %}fixed-top{% endif %} navbar-expand-lg navbar-light bg-white">

    {% if show_back_button|default(false) %}
        <a class="navbar-brand" href="javascript: history.back()">
            <i class="fas fa-arrow-left"></i> {{ 'menu.back'|trans }}
        </a>
    {% else %}
        <a class="navbar-brand" href="{{ path('property') }}">{{ site.name }}</a>
    {% endif %}

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% for item in site.menu %}

                <li class="nav-item">
                    <a class="nav-link"
                       href="{{ item.url }}"
                        {% if item.nofollow == true %} rel="nofollow" {% endif %}
                        {% if item.newTab == true %} target="_blank" {% endif %}
                    >
                        {{ item.title }}
                    </a>
                </li>

            {% endfor %}
        </ul>

        <ul class="navbar-nav ml-auto">

            {% if is_granted('ROLE_ADMIN') %}
                <li class="nav-item dropdown no-arrow">
                    <a class="nav-link dropdown-toggle"
                       href="#" id="userDropdown"
                       role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true"
                       aria-expanded="false">
                        {{ 'menu.admin'|trans }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="{{ path('admin_dashboard') }}">
                            {{ 'dashboard'|trans }}
                        </a>
                        <a class="dropdown-item" href="{{ path('user_property') }}">
                            {{ 'menu.account'|trans }}
                        </a>
                        <a class="dropdown-item" href="{{ path('admin_user_edit', {id: app.user.id}) }}">
                            {{ 'menu.edit_profile'|trans }}
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ path('security_logout') }}">
                            {{ 'menu.logout'|trans }}
                        </a>
                    </div>
                </li>
            {% elseif is_granted('ROLE_USER') %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('user_property') }}">{{ 'menu.account'|trans }}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('security_login') }}">{{ 'menu.login'|trans }}</a>
                </li>
            {% endif %}
        </ul>

    </div>
</nav>